### This in Exploratory Data Analysis in Polars library.

In [1]:
import polars as pl
import pandas as pd

In [2]:
%%time
df_csv1 = pl.read_csv("get_delhi.csv")

CPU times: user 26.2 ms, sys: 28.9 ms, total: 55 ms
Wall time: 53.3 ms

In [3]:
%%time
df_csv2 = pd.read_csv("get_delhi.csv")

CPU times: user 122 ms, sys: 47 ms, total: 169 ms
Wall time: 202 ms

In [4]:
df_csv.describe()

shape: (7, 19)
┌──────────┬──────────┬──────────┬────────────┬─────┬────────┬────────────┬────────────┬───────────┐
│ describe ┆ title    ┆ subtitle ┆ is_active_ ┆ ... ┆ price  ┆ built_up_a ┆ built_up_a ┆ emi       │
│ ---      ┆ ---      ┆ ---      ┆ property   ┆     ┆ ---    ┆ rea_value  ┆ rea_unit   ┆ ---       │
│ str      ┆ str      ┆ str      ┆ ---        ┆     ┆ str    ┆ ---        ┆ ---        ┆ str       │
│          ┆          ┆          ┆ f64        ┆     ┆        ┆ f64        ┆ str        ┆           │
╞══════════╪══════════╪══════════╪════════════╪═════╪════════╪════════════╪════════════╪═══════════╡
│ count    ┆ 21301    ┆ 21301    ┆ 21301.0    ┆ ... ┆ 21301  ┆ 21301.0    ┆ 21301      ┆ 21301     │
│ null_cou ┆ 0        ┆ 0        ┆ 0.0        ┆ ... ┆ 0      ┆ 0.0        ┆ 0          ┆ 0         │
│ nt       ┆          ┆          ┆            ┆     ┆        ┆            ┆            ┆           │
│ mean     ┆ null     ┆ null     ┆ 1.0        ┆ ... ┆ null   ┆ 1509.08727 ┆ null       ┆ null      │
│          ┆          ┆          ┆            ┆     ┆        ┆ 3          ┆            ┆           │
│ std      ┆ null     ┆ null     ┆ 0.0        ┆ ... ┆ null   ┆ 1659.46282 ┆ null       ┆ null      │
│          ┆          ┆          ┆            ┆     ┆        ┆ 2          ┆            ┆           │
│ min      ┆ 1 BHK    ┆ 1, 2, 3  ┆ 1.0        ┆ ... ┆ 1.0 Cr ┆ 26.0       ┆ sq.ft      ┆ ₹1.00 Lac │
│          ┆ Flat     ┆ BHK      ┆            ┆     ┆        ┆            ┆            ┆           │
│          ┆          ┆ Builder  ┆            ┆     ┆        ┆            ┆            ┆           │
│          ┆          ┆ Floors   ┆            ┆     ┆        ┆            ┆            ┆           │
│ max      ┆ Vikrant  ┆ 9990     ┆ 1.0        ┆ ... ┆ 99.0 L ┆ 96800.0    ┆ sq.yd      ┆ ₹99.79 K  │
│          ┆ Luxury   ┆ sq.ft    ┆            ┆     ┆        ┆            ┆            ┆           │
│          ┆ Floors   ┆ built up ┆            ┆     ┆        ┆            ┆            ┆           │
│          ┆          ┆ area     ┆            ┆     ┆        ┆            ┆            ┆           │
│ median   ┆ null     ┆ null     ┆ 1.0        ┆ ... ┆ null   ┆ 1200.0     ┆ null       ┆ null      │
└──────────┴──────────┴──────────┴────────────┴─────┴────────┴────────────┴────────────┴───────────┘

In [ ]:
df_csv.select(
    pl.col("foo")
)